INDEX_TERMS = {
    'Atmospheric Composition and Structure': {
        '0305 Aerosols and particles': [],  #Datatypes go in list
        '0310 Airglow and aurora': [],
        '0317 Chemical kinetic and photochemical properties': [],
        '0319 Cloud optics': [],
        '0320 Cloud physics and chemisty': [],
        '0322 Constituent sources and sinks': [],
        '0325 Evolution of the atmosphere': [],
        '0340 Middle atmosphere: composition and chemisty': [],
        '0341 Middle atmosphere: consituent transport and chemisty': [],
        '0342 Middle atmosphere: energy decomposition': [],
        '0343 Planetary atmospheres': [],
        '0345 Pollution: urban and regional': [],
        '0350 Pressure, density, and temperature': [],
        '0358 Thermosphere: energy deposition': [],
        '0360 Radiation: transmission and scattering': [],
        '0365 Troposhere: composition and chemistry': [],
        '0368 Troposhere: consituent transport and chemistry': [],
        '0370 Volcanic effects': [],
        '0394 Instruments and techniques': [],
    },
    'Atmospheric Processes': {
        '3304 Atmospheric electricity': [],
        '3305 Climate change and variability': [],
        '3307 Boundary layer processes': [],
        '3309 Climatology': [],
        '3310 Clouds and cloud feedbacks': [],
        '3311 Clouds and aerosols': [],
        '3314 Convective processes': [],
        '3315 Data assimilation': [],
        '3319 General circulation': [],
        '3324 Lightning': [],
        '3325 Monte Carlo technique': [],
        '3329 Mesoscale meteorology': [],
        '3332 Mesospheric dynamics': [],
        '3334 Middle atmosphere dynamics': [],
        '3336 Numerical approximations and analyses': [],
        '3337 Global climate models': [],
        '3344 Paleoclimatology': [],
        '3349 Polar meteorology': [],
        '3354 Precipitation': [],
        '3355 Regional modeling': [],
        '3359 Radiative processes': [],
        '3360 Remote sensing': [],
        '3364 Synoptic-scale meteorology': [],
        '3365 Subgrid-scale (SGS) parameterization': [],
        '3369 Thermospheric dynamics': [],
        '3371 Tropical convection': [],
        '3372 Tropical cyclones': [],
        '3373 Tropical dynamics': [],
        '3374 Tropical meteorology': [],
        '3379 Turbulence': [],
        '3389 Tides and planetary waves': [],
    },
    'Biogeosciences': {
        '0402 Agricultural systems': [],
        '0406 Astrobiology and extraterrestrial materials': [],
        '0408 Benthic processes': [],
        '0409 Bioavailability: chemical speciation and complexation': [],
        '0410 Biodiversity': [],
        '0412 Biogeochemical kinetics and reaction modeling': [],
        '0414 Biogeochemical cycles, processes, and modeling': [],
        '0416 Biogeophysics': [],
        '0418 Bioremediation': [],
        '0419 Biomineralization': [],
        '0420 Biomolecular and chemical tracers': [],
        '0424 Biosignatures and proxies': [],
        '0428 Carbon cycling': [],
        '0429 Climate dynamics': [],
        '0430 Computational methods and data processing': [],
        '0432 Contaminant and organic biogeochemistry': [],
        '0434 Data sets': [],
        '0438 Diel, seasonal, and annual cycles': [],
        '0439 Ecosystems, structure and dynamics': [],
        '0442 Estuarine and nearshore processes': [],
        '0444 Evolutionary geobiology': [],
        '0448 Geomicrobiology': [],
        '0452 Instruments and techniques': [],
        '0454 Isotopic composition and chemistry': [],
        '0456 Life in extreme environments': [],
        '0458 Limnology': [],
        '0459 Macro- and micropaleontology': [],
        '0460 Marine systems': [],
        '0461 Metals': [],
        '0465 Microbiology: ecology, physiology and genomics': [],
        '0466 Modeling': [],
        '0468 Natural hazards': [],
        '0469 Nitrogen cycling': [],
        '0470 Nutrients and nutrient cycling': [],
        '0473 Paleoclimatology and paleoceanography': [],
        '0475 Permafrost, cryosphere, and high-latitude processes': [],
        '0476 Plant ecology': [],
        '0478 Pollution: urban, regional and global': [],
        '0480 Remote sensing': [],
        '0483 Riparian systems': [],
        '0489 Trace element cycling': [],
        '0490 Trace gases': [],
        '0491 Food webs and trophodynamics': [],
        '0493 Urban systems': [],
        '0496 Water quality': [],
        '0497 Wetlands': [],
        '0498 General or miscellaneous': [],
    },
    'Computational Geophysics': {
        '0520 Data analysis: algorithms and implementation': [],
        '0530 Data presentation and visualization': [],
        '0545 Modeling': [],
        '0550 Model verification and validation': [],
        '0560 Numerical solutions': [],
    },
    'Cryosphere': {
        '0702 Permafrost': [],
        '0704 Seasonally frozen ground': [],
        '0710 Periglacial processes': [],
        '0720 Glaciers': [],
        '0724 Ice cores': [],
        '0726 Ice sheets': [],
        '0728 Ice shelves': [],
        '0730 Ice streams': [],
        '0736 Snow': [],
        '0738 Ice': [],
        '0740 Snowmelt': [],
        '0742 Avalanches': [],
        '0746 Lakes': [],
        '0750 Sea ice': [],
        '0754 Leads': [],
        '0758 Remote sensing': [],
        '0760 Engineering': [],
        '0762 Mass balance 0764 Energy balance': [],
        '0770 Properties': [],
        '0774 Dynamics': [],
        '0776 Glaciology': [],
        '0794 Instruments and techniques': [],
        '0798 Modeling': [],
    },
    'Education': {
        '0805 Elementary and secondary education': [],
        '0810 Post-secondary education': [],
        '0815 Informal education': [],
        '0820 Curriculum and laboratory design': [],
        '0825 Teaching methods': [],
        '0830 Teacher training': [],
        '0840 Evaluation and assessment': [],
        '0845 Instructional tools': [],
        '0850 Geoscience education research': [],
        '0855 Diversity': [],
    },
    'Electromagnetics': {
        '0619 Electromagnetic theory': [],
        '0689 Wave propagation': [],
        '0694 Instruments and techniques': [],
    },
    'Exploration Geophysics': {
        '0902 Computational methods: seismic': [],
        '0915 Downhole methods': [],
        '0920 Gravity methods': [],
        '0925 Magnetic and electrical methods': [],
        '0933 Remote sensing': [],
        '0935 Seismic methods': [],
        '0994 Instruments and techniques': [],
        '0999 General or miscellaneous': [],
    },
    'General or Miscellaneous': {
        '9805 Instruments useful in three or more fields': [],
        '9810 New fields (not classifiable under other headings)': [],
        '9815 Notices and announcements': [],
        '9820 Techniques applicable in three or more fields': [],
    },
    'Geochemistry': {
        '1009 Geochemical modeling': [],
        '1012 Reactions and phase equilibria': [],
        '1015 Composition of the core': [],
        '1020 Composition of the continental crust': [],
        '1021 Composition of the oceanic crust': [],
        '1025 Composition of the mantle': [],
        '1027 Composition of the planets': [],
        '1030 Geochemical cycles': [],
        '1032 Mid-oceanic ridge processes': [],
        '1033 Intra-plate processes': [],
        '1034 Hydrothermal systems': [],
        '1037 Magma genesis and partial melting': [],
        '1038 Mantle processes': [],
        '1039 Alteration and weathering processes': [],
        '1040 Radiogenic isotope geochemistry': [],
        '1041 Stable isotope geochemistry': [],
        '1043 Fluid and melt inclusion geochemistry': [],
        '1050 Marine geochemistry': [],
        '1051 Sedimentary geochemistry': [],
        '1055 Organic and biogenic geochemistry': [],
        '1060 Planetary geochemistry': [],
        '1065 Major and trace element geochemistry': [],
        '1090 Field relationships': [],
        '1094 Instruments and techniques': [],
    },
    'Geochronology': {
        '1105 Quaternary geochronology': [],
        '1115 Radioisotope geochronology': [],
        '1130 Geomorphological geochronology': [],
        '1140 Thermochronology': [],
        '1165 Sedimentary geochronology': [],
        '1194 Instruments and techniques': [],
    },
    'Geodesy and Gravity': {
        '1207 Transient deformation': [],
        '1209 Tectonic deformation': [],
        '1211 Non-tectonic deformation': [],
        '1214 Geopotential theory and determination': [],
        '1217 Time variable gravity': [],
        '1218 Mass balance': [],
        '1219 Gravity anomalies and Earth structure': [],
        '1220 Atmosphere monitoring with geodetic techniques': [],
        '1222 Ocean monitoring with geodetic techniques': [],
        '1225 Global change from geodesy': [],
        '1229 Reference systems': [],
        '1236 Rheology of the lithosphere and mantle': [],
        '1240 Satellite geodesy: results': [],
        '1241 Satellite geodesy: technical issues': [],
        '1242 Seismic cycle related deformations': [],
        '1243 Space geodetic surveys': [],
        '1294 Instruments and techniques': [],
        '1295 Integrations of techniques': [],
    },
    'Geographic Location': {
        '9305 Africa': [],
        '9310 Antarctica': [],
        '9315 Arctic region': [],
        '9345 Large bodies of water (e.g., lakes and inland seas)': [],
    },
    'Geomagnetism and Paleomagnetism': {
        '1505 Biogenic magnetic minerals': [],
        '1507 Core processes': [],
        '1510 Dynamo: theories and simulations': [],
        '1512 Environmental magnetism': [],
        '1515 Geomagnetic induction': [],
        '1517 Magnetic anomalies: modeling and interpretation': [],
        '1519 Magnetic mineralogy and petrology': [],
        '1520 Magnetostratigraphy': [],
        '1521 Paleointensity': [],
        '1522 Paleomagnetic secular variation': [],
        '1525 Paleomagnetism applied to tectonics: regional, global': [],
        '1527 Paleomagnetism applied to geologic processes': [],
        '1533 Remagnetization': [],
        '1540 Rock and mineral magnetism': [],
        '1541 Satellite magnetics: main field, crustal field, external field': [],
        '1550 Spatial variations attributed to seafloor spreading': [],
        '1560 Time variations: secular and longer': [],
        '1594 Instruments and techniques': [],
        '1595 Planetary magnetism: all frequencies and wavelengths': [],
    },
    'Global Change': {
        '1610 Atmosphere': [],
        '1615 Biogeochemical cycles, processes, and modeling': [],
        '1616 Climate variability': [],
        '1620 Climate dynamics': [],
        '1621 Cryospheric change': [],
        '1622 Earth system modeling': [],
        '1625 Geomorphology and weathering': [],
        '1626 Global climate models': [],
        '1627 Coupled models of the climate system': [],
        '1630 Impacts of global change': [],
        '1632 Land cover change': [],
        '1637 Regional climate change': [],
        '1640 Remote sensing': [],
        '1641 Sea level change': [],
        '1655 Water cycles': [],
        '1694 Instruments and techniques': [],
    },
    'History of Geophysics': {
        '1704 Atmospheric sciences': [],
        '1719 Hydrology': [],
        '1799 General or miscellaneous': [],
    },
    'Hydrology': {
        '1803 Anthropogenic effects': [],
        '1804 Catchment': [],
        '1805 Computational hydrology': [],
        '1806 Chemistry of fresh water': [],
        '1807 Climate impacts': [],
        '1808 Dams': [],
        '1809 Desertification': [],
        '1810 Debris flow and landslides': [],
        '1812 Drought': [],
        '1813 Eco-hydrology': [],
        '1814 Energy budgets': [],
        '1815 Erosion': [],
        '1816 Estimation and forecasting': [],
        '1817 Extreme events': [],
        '1818 Evapotranspiration': [],
        '1820 Floodplain dynamics': [],
        '1821 Floods': [],
        '1822 Geomechanics': [],
        '1823 Frozen ground': [],
        '1824 Geomorphology: general': [],
        '1825 Geomorphology: fluvial': [],
        '1826 Geomorphology: hillslope': [],
        '1827 Glaciology': [],
        '1828 Groundwater hydraulics': [],
        '1829 Groundwater hydrology': [],
        '1831 Groundwater quality': [],
        '1832 Groundwater transport': [],
        '1833 Hydroclimatology': [],
        '1834 Human impacts': [],
        '1835 Hydrogeophysics': [],
        '1836 Hydrological cycles and budgets': [],
        '1839 Hydrologic scaling': [],
        '1840 Hydrometeorology': [],
        '1842 Irrigation': [],
        '1845 Limnology': [],
        '1846 Model calibration': [],
        '1847 Modeling': [],
        '1848 Monitoring networks': [],
        '1849 Numerical approximations and analysis': [],
        '1852 Plant uptake': [],
        '1854 Precipitation': [],
        '1855 Remote sensing': [],
        '1856 River channels': [],
        '1858 Rocks: chemical properties': [],
        '1859 Rocks: physical properties': [],
        '1860 Streamflow': [],
        '1861 Sedimentation': [],
        '1862 Sediment transport': [],
        '1863 Snow and ice': [],
        '1865 Soils': [],
        '1866 Soil moisture': [],
        '1869 Stochastic hydrology': [],
        '1871 Surface water quality': [],
        '1873 Uncertainty assessment': [],
        '1874 Ungaged basins': [],
        '1875 Vadose zone': [],
        '1876 Water budgets': [],
        '1879 Watershed': [],
        '1880 Water management': [],
        '1884 Water supply': [],
        '1886 Weathering': [],
        '1890 Wetlands': [],
        '1894 Instruments and techniques: modeling': [],
        '1895 Instruments and techniques: monitoring': [],
    },
    'Informatics': {
        '1902 Community modeling frameworks': [],
        '1904 Community standards': [],
        '1906 Computational models, algorithms': [],
        '1908 Cyberinfrastructure': [],
        '1910 Data assimilation, integration and fusion': [],
        '1912 Data management, preservation, rescue': [],
        '1914 Data mining': [],
        '1916 Data and information discovery': [],
        '1918 Decision analysis': [],
        '1920 Emerging informatics technologies': [],
        '1922 Forecasting': [],
        '1926 Geospatial': [],
        '1928 GIS science': [],
        '1930 Data and information governance': [],
        '1932 High-performance computing': [],
        '1934 International collaboration': [],
        '1936 Interoperability': [],
        '1938 Knowledge representation and knowledge bases': [],
        '1942 Machine learning': [],
        '1946 Metadata': [],
        '1948 Metadata: Provenance': [],
        '1950 Metadata: Quality': [],
        '1952 Modeling': [],
        '1956 Numerical algorithms': [],
        '1958 Ontologies': [],
        '1964 Real-time and responsive information delivery': [],
        '1970 Semantic web and semantic integration': [],
        '1972 Sensor web': [],
        '1974 Social networks': [],
        '1976 Software tools and services': [],
        '1978 Software re-use': [],
        '1982 Standards': [],
        '1984 Statistical methods: Descriptive': [],
        '1986 Statistical methods: Inferential': [],
        '1990 Uncertainty': [],
        '1994 Visualization and portrayal': [],
        '1998 Workflow': [],
    },
    'Information Related to Geologic Time': {
        '9610 Cretaceous': [],
        '9619 Precambrian': [],
        '9699 General or miscellaneous': [],
    },
    'Interplanetary Physics': {
        '2101 Coronal mass ejections': [],
        '2104 Cosmic rays': [],
        '2109 Discontinuities': [],
        '2111 Ejecta, driver gases, and magnetic clouds': [],
        '2114 Energetic particles': [],
        '2124 Heliopause and solar wind termination': [],
        '2134 Interplanetary magnetic fields': [],
        '2139 Interplanetary shocks': [],
        '2144 Interstellar gas': [],
        '2151 Neutral particles': [],
        '2159 Plasma waves and turbulence': [],
        '2162 Solar cycle variations': [],
        '2164 Solar wind plasma': [],
        '2169 Solar wind sources': [],
        '2194 Instruments and techniques': [],
    },
    'Ionosphere': {
        '2403 Active experiments': [],
        '2407 Auroral ionosphere': [],
        '2409 Current systems': [],
        '2415 Equatorial ionosphere': [],
        '2435 Ionospheric disturbances': [],
        '2437 Ionospheric dynamics': [],
        '2439 Ionospheric irregularities': [],
        '2441 Ionospheric storms': [],
        '2443 Midlatitude ionosphere': [],
        '2447 Modeling and forecasting': [],
        '2461 Plasma interactions with dust and aerosols': [],
        '2471 Plasma waves and instabilities': [],
        '2475 Polar cap ionosphere': [],
        '2487 Wave propagation': [],
        '2494 Instruments and techniques': [],
    },
    'Magnetospheric Physics': {
        '2704 Auroral phenomena': [],
        '2721 Field-aligned currents and current systems': [],
        '2723 Magnetic reconnection': [],
        '2724 Magnetopause and boundary layers': [],
        '2728 Magnetosheath': [],
        '2730 Magnetosphere: inner': [],
        '2732 Magnetosphere interactions with satellites and rings': [],
        '2740 Magnetospheric configuration and dynamics': [],
        '2744 Magnetotail': [],
        '2752 MHD waves and instabilities': [],
        '2753 Numerical modeling': [],
        '2756 Planetary magnetospheres': [],
        '2760 Plasma convection': [],
        '2764 Plasma sheet': [],
        '2768 Plasmasphere': [],
        '2772 Plasma waves and instabilities': [],
        '2774 Radiation belts': [],
        '2776 Polar cap phenomena': [],
        '2778 Ring current': [],
        '2780 Solar wind interactions with unmagnetized bodies': [],
        '2788 Magnetic storms and substorms': [],
        '2790 Substorms': [],
        '2794 Instruments and techniques': [],
    },
    'Marine Geology and Geophysics': {
        '3002 Continental shelf and slope processes': [],
        '3004 Gas and hydrate systems': [],
        '3017 Hydrothermal systems': [],
        '3020 Littoral processes': [],
        '3022 Marine sediments: processes and transport': [],
        '3025 Marine seismics': [],
        '3030 Micropaleontology': [],
        '3035 Midocean ridge processes': [],
        '3036 Ocean drilling': [],
        '3037 Oceanic hotspots and intraplate volcanism': [],
        '3039 Oceanic transform and fracture zone processes': [],
        '3040 Plate tectonics': [],
        '3042 Ophiolites': [],
        '3045 Seafloor morphology, geology, and geophysics': [],
        '3050 Ocean observatories and experiments': [],
        '3070 Submarine landslides': [],
        '3075 Submarine tectonics and volcanism': [],
    },
    'Mathematical Geophysics': {
        '3225 Numerical approximations and analysis': [],
        '3252 Spatial analysis': [],
        '3260 Inverse theory': [],
        '3265 Stochastic processes': [],
        '3270 Time series analysis': [],
        '3275 Uncertainty quantification': [],
        '3299 General or miscellaneous': [],
    },
    'Mineral Physics': {
        '3902 Creep and deformation': [],
        '3909 Elasticity and anelasticity': [],
        '3914 Electrical properties': [],
        '3919 Equations of state': [],
        '3924 High-pressure behavior': [],
        '3939 Physical thermodynamics': [],
        '3949 Thermal expansivity': [],
        '3954 X-ray, neutron, and electron spectroscopy and diffraction': [],
        '3994 Instruments and techniques': [],
    },
    'Mineralogy and Petrology': {
        '3612 Reactions and phase equilibria': [],
        '3617 Alteration and weathering processes': [],
        '3618 Magma chamber processes': [],
        '3621 Mantle processes': [],
        '3625 Petrography, microstructures, and textures': [],
        '3630 Experimental mineralogy and petrology': [],
        '3651 Thermobarometry': [],
        '3652 Pressure-temperature-time paths': [],
        '3653 Fluid flow': [],
        '3654 Ultra-high pressure metamorphism': [],
        '3660 Metamorphic petrology': [],
        '3672 Planetary mineralogy and petrology': [],
        '3675 Sedimentary petrology': [],
    },
    'Natural Hazards': {
        '4302 Geological': [],
        '4304 Oceanic': [],
        '4305 Space weather': [],
        '4306 Multihazards': [],
        '4313 Extreme events': [],
        '4314 Mathematical and computer modeling': [],
        '4315 Monitoring, forecasting, prediction': [],
        '4316 Physical modeling': [],
        '4317 Precursors': [],
        '4318 Statistical analysis': [],
        '4319 Spatial modeling': [],
        '4321 Climate impact': [],
        '4322 Health impact': [],
        '4323 Human impact': [],
        '4324 Spatial decision support systems': [],
        '4327 Resilience': [],
        '4328 Risk': [],
        '4329 Sustainable development': [],
        '4330 Vulnerability': [],
        '4331 Disaster relief': [],
        '4332 Disaster resilience': [],
        '4333 Disaster risk analysis and assessment': [],
        '4334 Disaster risk communication': [],
        '4335 Disaster management': [],
        '4336 Economic impacts of disasters': [],
        '4337 Remote sensing and disasters': [],
        '4339 Disaster mitigation': [],
        '4341 Early warning systems': [],
        '4342 Emergency management': [],
        '4343 Preparedness and planning': [],
        '4345 Community management': [],
        '4347 Recovery and reconstruction after disaster': [],
        '4352 Interaction between science and disaster management authorities': [],
        '4353 Sociology of disasters': [],
    },
    'Nonlinear Geophysics': {
        '4420 Chaos': [],
        '4430 Complex systems': [],
        '4440 Fractals and multifractals': [],
        '4445 Nonlinear differential equations': [],
        '4460 Pattern formation': [],
        '4468 Probability distributions, heavy and fat-tailed': [],
        '4475 Scaling: spatial and temporal': [],
        '4485 Self-organization': [],
        '4490 Turbulence': [],
    },
    'Oceanography: Biological and Chemical': {
        '4805 Biogeochemical cycles, processes, and modeling': [],
        '4807 Chemical speciation and complexation': [],
        '4815 Ecosystems, structure, dynamics, and modeling': [],
        '4817 Food webs, structure, and dynamics': [],
        '4825 Geochemistry': [],
        '4840 Microbiology and microbial ecology': [],
        '4858 Population dynamics and ecology': [],
        '4860 Radioactivity and radioisotopes': [],
        '4875 Trace elements': [],
        '4894 Instruments, sensors, and techniques': [],
        '4899 General or miscellaneous': [],
    },
    'Oceanography: General': {
        '4207 Arctic and Antarctic oceanography': [],
        '4215 Climate and interannual variability': [],
        '4217 Coastal processes': [],
        '4219 Continental shelf and slope processes': [],
        '4220 Coral reef systems': [],
        '4231 Equatorial oceanography': [],
        '4235 Estuarine processes': [],
        '4255 Numerical modeling': [],
        '4262 Ocean observing systems': [],
        '4263 Ocean predictability and prediction': [],
        '4273 Physical and biogeochemical interactions': [],
        '4275 Remote sensing and electromagnetic processes': [],
        '4279 Upwelling and convergences': [],
        '4294 Instruments and techniques': [],
        '4299 General or miscellaneous': [],
    },
    'Oceanography: Physical': {
        '4508 Coriolis effects': [],
        '4512 Currents': [],
        '4513 Decadal ocean variability': [],
        '4516 Eastern boundary currents': [],
        '4520 Eddies and mesoscale processes': [],
        '4522 ENSO': [],
        '4528 Fronts and jets': [],
        '4532 General circulation': [],
        '4544 Internal and inertial waves': [],
        '4546 Nearshore processes': [],
        '4556 Sea level: variations and mean': [],
        '4558 Sediment transport': [],
        '4560 Surface waves and tides': [],
        '4564 Tsunamis and storm surges': [],
        '4568 Turbulence, diffusion, and mixing processes': [],
        '4572 Upper ocean and mixed layer processes': [],
        '4576 Western boundary currents': [],
        '4594 Instruments and techniques': [],
    },
    'Paleoceanography': {
        '4904 Atmospheric transport and circulation': [],
        '4910 Astronomical forcing': [],
        '4912 Biogeochemical cycles, processes, and modeling': [],
        '4914 Continental climate records': [],
        '4924 Geochemical tracers': [],
        '4926 Glacial': [],
        '4928 Global climate models': [],
        '4930 Greenhouse gases': [],
        '4934 Insolation forcing': [],
        '4936 Interglacial': [],
        '4938 Interhemispheric phasing': [],
        '4944 Micropaleontology': [],
        '4950 Paleoecology': [],
        '4954 Sea surface temperature': [],
        '4960 Stadial': [],
        '4962 Thermohaline': [],
        '4994 Instruments and techniques': [],
    },
    'Physical Properties of Rocks': {
        '5102 Acoustic properties': [],
        '5104 Fracture and flow': [],
        '5112 Microstructure': [],
        '5114 Permeability and porosity': [],
        '5120 Plasticity, diffusion, and creep': [],
        '5139 Transport properties': [],
        '5194 Instruments and techniques': [],
    },
    'Planetary Sciences: Astrobiology': {
        '5205 Formation of stars and planets': [],
        '5210 Planetary atmospheres, clouds, and hazes': [],
        '5215 Origin of life': [],
        '5220 Hydrothermal systems and weathering on other planets': [],
        '5225 Early environment of Earth': [],
    },
    'Planetary Sciences: Comets and Small Bodies': {
        '6005 Atmospheres': [],
        '6008 Composition': [],
        '6015 Dust': [],
        '6022 Impact phenomena': [],
        '6023 Comets: dust tails and trails': [],
        '6024 Interiors': [],
        '6040 Origin and evolution': [],
        '6045 Physics and chemistry of materials': [],
        '6055 Surfaces': [],
        '6099 General or miscellaneous': [],
    },
    'Planetary Sciences: Fluid Planets': {
        '5704 Atmospheres': [],
        '5709 Composition': [],
        '5714 Gravitational fields': [],
        '5724 Interiors': [],
        '5737 Magnetospheres': [],
        '5759 Rings and dust': [],
        '5799 General or miscellaneous': [],
    },
    'Planetary Sciences: Solar System Objects': {
        '6205 Asteroids': [],
        '6207 Comparative planetology': [],
        '6210 Comets': [],
        '6213 Dust': [],
        '6218 Jovian satellites': [],
        '6219 Io': [],
        '6221 Europa': [],
        '6225 Mars': [],
        '6230 Martian satellites': [],
        '6235 Mercury': [],
        '6240 Meteorites and tektites': [],
        '6250 Moon': [],
        '6260 Neptunian satellites': [],
        '6265 Planetary rings': [],
        '6270 Pluto and satellites': [],
        '6275 Saturn': [],
        '6280 Saturnian satellites': [],
        '6281 Titan': [],
        '6282 Enceladus': [],
        '6290 Uranian satellites': [],
        '6295 Venus': [],
        '6296 Extra-solar planets': [],
        '6297 Instruments and techniques': [],
    },
    'Planetary Sciences: Solid Surface Planets': {
        '5405 Atmospheres': [],
        '5410 Composition': [],
        '5415 Erosion and weathering': [],
        '5418 Heat flow': [],
        '5419 Hydrology and fluvial processes': [],
        '5422 Ices': [],
        '5430 Interiors': [],
        '5435 Ionospheres': [],
        '5440 Magnetic fields and magnetism': [],
        '5443 Magnetospheres': [],
        '5445 Meteorology': [],
        '5455 Origin and evolution': [],
        '5460 Physical properties of materials': [],
        '5464 Remote sensing': [],
        '5465 Rings and dust': [],
        '5470 Surface materials and properties': [],
        '5475 Tectonics': [],
        '5480 Volcanism': [],
        '5494 Instruments and techniques': [],
    },
    'Policy Sciences': {
        '6304 Benefit-cost analysis': [],
        '6309 Decision making under uncertainty': [],
        '6319 Institutions': [],
        '6324 Legislation and regulations': [],
        '6329 Project evaluation': [],
        '6344 System operation and management': [],
        '6349 General or miscellaneous': [],
    },
    'Public Issues': {
        '6610 Funding': [],
        '6620 Science policy': [],
        '6630 Workforce': [],
        '6699 General or miscellaneous': [],
    },
    'Radio Science': {
        '6934 Ionospheric propagation': [],
        '6979 Space and satellite communication': [],
    },
    'Seismology': {
        '7203 Body waves': [],
        '7205 Continental crust': [],
        '7207 Core': [],
        '7208 Mantle': [],
        '7209 Earthquake dynamics': [],
        '7212 Earthquake ground motions and engineering seismology': [],
        '7215 Earthquake source observations': [],
        '7218 Lithosphere': [],
        '7219 Seismic monitoring and test-ban treaty verification': [],
        '7221 Paleoseismology': [],
        '7223 Earthquake interaction, forecasting, and prediction': [],
        '7230 Seismicity and tectonics': [],
        '7240 Subduction zones': [],
        '7245 Mid-ocean ridges': [],
        '7260 Theory': [],
        '7270 Tomography': [],
        '7280 Volcano seismology': [],
        '7290 Computational seismology': [],
        '7294 Seismic instruments and networks': [],
    },
    'Solar Physics, Astrophysics, and Astronomy': {
        '7507 Chromosphere': [],
        '7509 Corona': [],
        '7511 Coronal holes': [],
        '7513 Coronal mass ejections': [],
        '7514 Energetic particles': [],
        '7519 Flares': [],
        '7524 Magnetic fields': [],
        '7526 Magnetic reconnection': [],
        '7529 Photosphere': [],
        '7534 Radio emissions': [],
        '7536 Solar activity cycle': [],
        '7544 Stellar interiors and dynamo theory': [],
        '7546 Transition region': [],
        '7594 Instruments and techniques': [],
        '7599 General or miscellaneous': [],
    },
    'Space Plasma Physics': {
        '7823 Ionization processes': [],
        '7827 Kinetic and MHD theory': [],
        '7829 Kinetic waves and instabilities': [],
        '7831 Laboratory studies and experimental techniques': [],
        '7833 Mathematical and numerical techniques': [],
        '7835 Magnetic reconnection': [],
        '7836 MHD waves and instabilities': [],
        '7845 Particle acceleration': [],
        '7846 Plasma energization': [],
        '7849 Plasma interactions with dust and aerosols': [],
        '7851 Shock waves': [],
        '7863 Turbulence': [],
    },
    'Space Weather': {
        '7904 Geomagnetically induced currents': [],
        '7924 Forecasting': [],
        '7938 Impacts on humans': [],
        '7944 Ionospheric effects on radio waves': [],
        '7949 Ionospheric storms': [],
        '7954 Magnetic storms': [],
        '7959 Models': [],
        '7974 Solar effects': [],
        '7984 Space radiation environment': [],
        '7999 General or miscellaneous': [],
    },
    'Structural Geology': {
        '8004 Dynamics and mechanics of faulting': [],
        '8010 Fractures and faults': [],
        '8011 Kinematics of crustal and mantle deformation': [],
        '8012 High strain deformation zones': [],
        '8020 Mechanics, theory, and modeling': [],
        '8031 Rheology: crust and lithosphere': [],
        '8040 Remote sensing': [],
        '8045 Role of fluids': [],
    },
    'Tectonophysics': {
        '8103 Continental cratons': [],
        '8104 Continental margins: convergent': [],
        '8105 Continental margins: divergent': [],
        '8107 Continental neotectonics': [],
        '8108 Continental tectonics: compressional': [],
        '8109 Continental tectonics: extensional': [],
        '8110 Continental tectonics: general': [],
        '8111 Continental tectonics: strike-slip and transform': [],
        '8118 Dynamics and mechanics of faulting': [],
        '8120 Dynamics of lithosphere and mantle: general': [],
        '8121 Dynamics: convection currents, and mantle plumes': [],
        '8122 Dynamics: gravity and tectonics': [],
        '8123 Dynamics: seismotectonics': [],
        '8124 Earth\'s interior: composition and state': [],
        '8125 Evolution of the Earth': [],
        '8130 Heat generation and transport': [],
        '8135 Hydrothermal systems': [],
        '8137 Hotspots, large igneous provinces, and flood basalt volcanism': [],
        '8138 Lithospheric flexure': [],
        '8139 Obduction tectonics': [],
        '8140 Ophiolites': [],
        '8145 Physics of magma and magma bodies': [],
        '8147 Planetary interiors': [],
        '8148 Planetary volcanism': [],
        '8149 Planetary tectonics': [],
        '8150 Plate boundary: general': [],
        '8155 Plate motions: general': [],
        '8157 Plate motions: past': [],
        '8159 Rheology: crust and lithosphere': [],
        '8160 Rheology: general': [],
        '8162 Rheology: mantle': [],
        '8163 Rheology and friction of fault zones': [],
        '8164 Stresses: crust and lithosphere': [],
        '8168 Stresses: general': [],
        '8169 Sedimentary basin processes': [],
        '8170 Subduction zone processes': [],
        '8175 Tectonics and landscape evolution': [],
        '8177 Tectonics and climatic interactions': [],
        '8178 Tectonics and magmatism': [],
        '8180 Tomography': [],
        '8185 Volcanic arcs': [],
        '8194 Instruments and techniques': [],
    },
}
